### ISSUE TITLE
Template different de l'officiel

### ISSUE THREAD

**Issue by gremi64** [soywod/attestation-deplacement-derogatoire#2]
Le template du pdf (v2, mis a jour il y a 3h environ), n'est pas celui proposé sur le site officiel du gouvernement.

Ils ont changé de repo git (rip...) : https://github.com/LAB-MI/attestation-deplacement-derogatoire-q4-2020

Première phrase du pdf officiel : "En application du décret n°2020-1310 du 29 octobre 2020 prescrivant les mesures générales 
nécessaires pour faire face à l'épidémie de Covid19 dans le cadre de l'état d'urgence sanitaire" 

Super appli en tout cas, simple et efficace !  <3

**Comment by soywod** [comment]
Ah oui effectivement, mais c'est bizarre parce que j'ai pris le template [directement du site du gouvernement](https://www.interieur.gouv.fr/content/download/124831/999556/file/30-10-2020-attestation-de-deplacement-derogatoire.pdf?#xtor=AD-322) et il a pas la même tête du tout que celui du repo git ... Je serais d'avis de se baser sur le document généré par leur app web https://media.interieur.gouv.fr/deplacement-covid-19/, qui correspond à celle que j'ai dans mon app mobile. Qu'en penses-tu ?

**Comment by gremi64** [comment]
Quand je génère a partir de leur web app, j'ai la phrase "... 29 octobre..."

Du coup je suis totalement d'accord avec ta phrase : "Je serais d'avis de se baser sur le document généré par leur app web https://media.interieur.gouv.fr/deplacement-covid-19/"
Mais si on ne génère pas le même fichier a partir de leur web app... c'est encore plus étrange xD

Voilà le document que je viens de générer avec la web app officielle 
[attestation-2020-10-31_08-54.pdf](https://github.com/soywod/attestation-deplacement-derogatoire/files/5468742/attestation-2020-10-31_08-54.pdf)

**Comment by soywod** [comment]
Mais c'est super étrange, voilà ce que j'ai de mon côté quand j'utilise leur web app ...

[attestation-2020-10-31_09-08.pdf](https://github.com/soywod/attestation-deplacement-derogatoire/files/5468759/attestation-2020-10-31_09-08.pdf)

Du coup je vais ptet me baser sur celle de github ...

**Comment by gremi64** [comment]
Tellement bizarre O_o

Fais comme tu le sens alors, les 2 sont peut être valides... ?

Tu peux clôturer l'issue bien évidemment :)

**Comment by soywod** [comment]
Je vais prendre ta version qui me semble plus aboutie (surtout vue l'entête). Merci en tout cas pour le coup de main ! Je suis en train de le changer, je vais déployer très prochainement.
