### ISSUE TITLE
Gestion multi-profils

### ISSUE THREAD

**Issue by Yes21** [soywod/attestation-deplacement-derogatoire#3]
Bonjour,
Suite à mon commentaire sur googleplay au sujet de multiples profils, je souhaite vous soumettre une proposition d'implémentation de cette fonctionnalité qui ne bouleverserait pas l'interface.

- Il faudrait rajouter un champ pour nommer chaque profil. Le premier profil créé à l'initialisation pourrait être automatiquement  nommer "Principal" (ou autre).
- Ensuite, il suffirait de rajouter sur la page "Profil" (obtenue en cliquant "Profil" depuis la page "Motif(s)) : 
          - un bouton "+", pour créer un nouveau profil (en lui donnant un nom),
          - puis une liste déroulante pour changer de profil.

Voilà, j'espère que cette proposition vous semblera constructive ...

Bien cordialement.

Yes21

**Comment by soywod** [comment]
Bonjour,
J'ai beaucoup réfléchi sur le sujet aujourd'hui, et je suis arrivé à la même conclusion que vous donc ça me rassure. Je suis en train de déployer la 1.7 actuellement qui améliore les formulaires et l'UX de façon générale. Demain je m'attaque à ces profils. Je vous tiens au courant.

**Comment by Yes21** [comment]
Tant mieux si ma proposition rejoint votre analyse.
En attendant, je vous remerci pour les améliorations de la 1.7.

Ps : j'aimerais vous soutenir financièrement, mais n'ai pas trouvé de lien pour vous faire un don ...

**Comment by soywod** [comment]
La 1.8 ne devrait pas tarder, avec l'ajout du multi-profils. Je test encore pour être sûr de ne rien casser. Je vous tiens au courant quand c'est en ligne.

Pour le don, ça serait vraiment adorable ! J'ai 3 plateformes à vous proposer :  
- [Ko-fi](https://ko-fi.com/soywod)
- [PayPal](https://www.paypal.com/paypalme/soywod)
- [Patreon](https://www.patreon.com/soywod/creators)

**Comment by soywod** [comment]
La 1.8 est en cours de déploiement, vous devriez la recevoir cette nuit. Merci pour votre aide, et n'hésitez-pas à réouvrir l'issue si vous trouvez des bugs ou si vous avez des idées d'amélioration.

**Comment by Yes21** [comment]
Un grand merci pour les profils multiples.
J'admire la manière simple et ergonomique dont vous avez implémenté cette fonctionnalité.
Bravo ++ Il n'y a rien à rajouter.
Votre appli est maintenant la meilleure de la catégorie.

Comptez sur moi pour un petit coup de pouce financier.

Merci encore.

Yves
