### ISSUE TITLE
L'application crash après mise à jour 1.8

### ISSUE THREAD

**Issue by Zalaxx** [soywod/attestation-deplacement-derogatoire#4]
Après avoir mis à jour l'application de la version 1.7 à 1.8, l'application ne veut plus s'ouvrir avec comme message (popup Android) "AttestationDeplacement... keeps stopping". Je suis sur Android 10 (avec Calyx OS: https://calyxos.org/).
J'ai donc essayé de réinstaller l'application. Tout marchait bien, jusqu'à la génération du PDF (ou la preview?), où l'application crash. Après, impossible de réouvrir l'application (puisque tente de s'ouvrir en montrant une preview du pdf).
Si vous avez besoin d'informations supplémentaires, ou d'aide pour tester des patchs, n'hésitez pas, j'essaierai d'aider dans la mesure du possible.

Ps: Super app, très simple à utiliser et très pratique :)

**Comment by soywod** [comment]
Aïe, ça sent pas bon ça. Je vais regarder la console Google voir si je trouve pas votre erreur avec plus d'informations. À la 1.7 ça ne plantait jamais ?

**Comment by Zalaxx** [comment]
Aucun problème sur la 1.7, ça marchait également parfaitement sur 2 autres appareils (Android 9 ou 8 je dirais, un Samsung et un Honor avec le système de base). Je pourrais essayer de mettre à jour sur l'un des deux voir si je peux reproduire l'issue.

**Comment by soywod** [comment]
Je n'arrive pas à trouver de traces dans la console. Ça plante à l'affichage du pdf (écran "Attestation") ou au téléchargement (après avoir cliqué sur "Télécharger") ? C'est étrange parce que je n'ai pas touché cette partie dans la dernière mise à jour. J'ai principalement retouché la section des profils. D'ailleurs cette section marche bien, pas de plantage ?

>  Je pourrais essayer de mettre à jour sur l'un des deux voir si je peux reproduire l'issue.

Oui je veux bien, si ça peut aider. Je n'ai vraiment pas de piste là. Essayez peut-être de vider le cache de l'appli et de recommencer ?

**Comment by soywod** [comment]
Est-ce que votre téléphone ne serait pas un Samsung Galaxy Grand Neo Plus ?

**Comment by Zalaxx** [comment]
Je viens d'essayer sur un Honor 9 Lite avec le système de base (Android 9.1 et EMUI 9), tout marchait bien.
Mon appareil (celui sur lequel ça ne fonctionne pas) est un Google Pixel 3 XL avec CalyxOs (donc pas de services Google mais MicroG). Je l'ai pas le temps d'appuyer sur le bouton Télécharger, je vois seulement l'icon de chargement quelques instants (avec le bouton retour et Télécharger en haut) avant que ça crash.

Si je me souvient bien, à la première génération d'un PDF dans l'application, il y a une demande du Play Store pour noter d'application. Puisque je n'ai pas les services Google, peut être que c'est ça qui causerait le problème ?

**Comment by soywod** [comment]
> Mon appareil est un Google Pixel 3 XL avec CalyxOs (donc pas de services Google mais MicroG)

Je pense que c'est l'info qui me manquait. J'avais pensé à ce module (qui se déclenche effectivement après une génération d'attestation) et je n'y croyais pas trop, mais avec MicroG ça prend sens. J'ai cherché sur le sujet mais je ne trouve rien. Je vais tenter quelque chose dans la prochaine version, en espérant que ça résolve le problème. Sinon il faudrait que je sorte une version sans ce module. Je vous tiens au courant. Merci pour votre aide :)

**Comment by soywod** [comment]
PS : ça marchait avant parce que je limitais moi-même l'apparition de cette popup. Mais j'ai appris que Google le fait lui-même donc j'ai enlevé mon filtre, d'où votre erreur dans cette version !

**Comment by Zalaxx** [comment]
J'ai rapidement regardé le dernier commit, et c'est quand j'ai vu qu'il y avait un changement autour du RequestInAppReview que j'y ai pensé. Ça m'étonne quand même que ça fasse planter toute l'application juste à cause de ça, mais bon, ça reste le plus plausible. J'attend la prochaine release alors, merci :)

**Comment by soywod** [comment]
Je vais tenter d'englober ces appels dans un `try...catch`, à voir. Je release après manger :)

**Comment by soywod** [comment]
J'ai trouvé une lib super intéressante, je mets ça en place et je déploie ! https://github.com/a7ul/react-native-exception-handler

**Comment by soywod** [comment]
La version 1.9 est en ligne, n'hésitez pas à réouvrir l'issue si besoin ;)

**Comment by Zalaxx** [comment]
Le problème semble persister.. (j'ai réinstallé pour vérifier, et même après réinstallation, ça ne fonctionne pas).
J'ai bien un message d'erreur au lieu d'un crash (je peux confirmer que ça vient du AppReviewModule, avec l'erreur "Failed to bind to the service" suivi de toute la pile).
Une capture d'écran de ce que je reçoit :
<img height="450px" src="https://user-images.githubusercontent.com/35188982/98025373-7dd76200-1e01-11eb-9f83-2a986d77a020.png">
Et comme à chaque fois l'application veut réouvrir sur la preview du pdf, je suis bloqué sur le message d'erreur (ce qui est en soi une avancé, puisque l'application en elle même ne crash plus mais affiche un message d'erreur).
J'ai bien essayé de build l'application pour tester de mon côté, mais n'ayant jamais fait de développement mobile, je n'ai pas toute la toolchain et les outils nécessaires. Mais si je peux aider pour quoi que ce soit, je suis disponible :)

**Comment by soywod** [comment]
Donc ça veut dire que c'est une erreur native et non javascript, je ne suis pas sûr d'avoir la main dessus avec React Native :/ je continue les recherches.

**Comment by soywod** [comment]
J'ai trouvé cette lib qui pourrait peut-être faire l'affaire, je testerai dans la prochaine mise à jour : https://github.com/UCSD/react-native-google-api-availability-bridge

**Comment by soywod** [comment]
J'ai rajouté cette lib dans la `2.3` qui devrait être en ligne d'ici quelques heures. Tenez-moi au courant !
