### ISSUE TITLE
permissions réseaux / wifi inutiles ?

### ISSUE THREAD

**Issue by oddskool** [soywod/attestation-deplacement-derogatoire#5]
Bonjour,

(merci pour cette appli, je pense qu'elle rend le confinement plus simple à beaucoup de monde, bravo pour cette appli clairement open-source)

Il me semble que les permissions demandées soient un peu inutiles/exagérées par rapport à la fonctionnalité:
- full network access
- view Wi-Fi connections

Certaines personnes peuvent trouver ces permissions en contradiction avec ce qui est affiché:
✔ Fonctionne hors-ligne

Si elles ne sont effectivement pas utiles, pouvez-vous les retirer ?
Si elles sont utiles (par ex à des fins de déboguage) je suggèrerait de le préciser :)

**Comment by soywod** [comment]
Je crois que ces permissions sont demandées par la lib [NetInfo](https://github.com/react-native-netinfo/react-native-netinfo) que j'utilise pour détecter [si l'appareil est connecté ou pas](https://github.com/soywod/attestation-deplacement-derogatoire/blob/9afc93bb9fa6ee253b8ac7e2a5522c070abc5c4b/src/pdf.tsx#L256-L260) et afficher la popup de review Google Play en fonction. Dans l'absolu je pourrais enlever ce test, ça ne ferait pas planter l'application et ça éviterait d'avoir cette permission. Je ferai le nécessaire dans la prochaine version. Merci pour votre précieux avis :)

**Comment by soywod** [comment]
> Si elles sont utiles (par ex à des fins de déboguage) je suggèrerait de le préciser :)

Dans tous les cas, un petit paragraphe sur l'utilisation des permissions est une bonne idée, je rajouterai ça dans la description de la fiche Google Play !

**Comment by soywod** [comment]
J'ai enlevé cette permission, il ne reste plus que la permission du Stockage qui est demandée au moment du téléchargement. Ça sera effectif à partir de la `2.3` qui sera dispo d'ici quelques heures. Merci pour votre aide !
