### ISSUE TITLE
Mémorisation des cases précédentes

### ISSUE THREAD

**Issue by achanu** [soywod/attestation-deplacement-derogatoire#6]
Bonjour,

Lors de la génération d'une attestation, serait-il possible d'avoir les cases pré-cochées correspondant à la précédente génération d'attestation.

**Comment by soywod** [comment]
Bonjour,
Merci pour cette proposition mais j'ai peur que ça en bloque plus d'un. Pas tout le monde regénère les mêmes attestations à chaque fois. Il est possible d'avoir ce comportement via la fonction "Dupliquer", qui reprend les mêmes raisons et la même heure de départ.
