### ISSUE TITLE
Page de crédits

### ISSUE THREAD

**Issue by achanu** [soywod/attestation-deplacement-derogatoire#7]
Bonjour,

Serait-il possible d'ajouter une page de crédits avec des éléments tels que les licences, le lien du github, la version actuelle, et peux être d'autres informations.

**Comment by soywod** [comment]
Bonjour,
C'est prévu pour la prochaine version, si j'arrive à me dégager un peu de temps semaine prochaine.

**Comment by soywod** [comment]
La page de crédits a été ajoutée dans la `v2.4.1` qui sera disponible cette nuit. Merci !
